"""
pharmacy_common.py — shared engine used by the scripts.

Do NOT edit this file. All the settings you'd want to change live in
config.py instead.
"""

import csv
import hashlib
import re
import sqlite3
from datetime import datetime

import config

# ---------------------------------------------------------------------
# Text normalization
# ---------------------------------------------------------------------

def _normalize(text):
    """Lowercase and strip everything but letters/digits, so 'Ins.Code:',
    'ins code', and 'INSCODE' all compare equal."""
    return re.sub(r"[^a-z0-9]", "", str(text).lower())


# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------

def get_connection():
    config.BASE_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(config.DB_PATH))
    conn.row_factory = sqlite3.Row
    return conn


def _sql_real(col):
    """SQLite expression: a money-ish text column ('1,892.20', '$5 ')
    read as a REAL, tolerating thousands commas, '$' and spaces."""
    return (
        "CAST(REPLACE(REPLACE(REPLACE(COALESCE(" + col
        + ", ''), ',', ''), '$', ''), ' ', '') AS REAL)"
    )


def _payment_due_expr(prefix=""):
    """SQLite expression for  payment_due = insurance_paid - payment_received,
    formatted to 2 decimals. `prefix` is '' (bare columns) or 'NEW.'
    (inside a trigger)."""
    return (
        "printf('%.2f', "
        + _sql_real(prefix + "insurance_paid")
        + " - "
        + _sql_real(prefix + "payment_received")
        + ")"
    )


def ensure_schema(conn):
    """Create the table from config.ALL_FIELDS if it doesn't exist yet,
    and — if it already exists — ADD any ALL_FIELDS column it's missing.

    SQLite can add a column but not drop or rename one, so after you
    rename/remove an entry in ALL_FIELDS the old column just sits there
    unused (harmless; it's not in the export). Every model column
    defaults to '' so a field an import doesn't supply reads as blank,
    not NULL. rx_number + filled_date are hidden bookkeeping columns used
    only as the de-dup key.

    Also installs two triggers that keep `payment_due` equal to
    `insurance_paid - payment_received`: one fills it on INSERT when it
    came in blank, the other recomputes it whenever either input is
    changed (by a script, by DB Browser, by anything)."""
    col_defs = [f"{col} TEXT DEFAULT ''" for col, _ in config.ALL_FIELDS]
    body = ",\n            ".join(col_defs)
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {config.TABLE_NAME} (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            {body},
            rx_number TEXT,
            filled_date TEXT,
            source_file TEXT,
            imported_at TEXT,
            UNIQUE(rx_number, filled_date)
        )
        """
    )

    existing = {row[1] for row in conn.execute(
        f"PRAGMA table_info({config.TABLE_NAME})"
    )}
    for col, _ in config.ALL_FIELDS:
        if col not in existing:
            conn.execute(
                f"ALTER TABLE {config.TABLE_NAME} ADD COLUMN {col} TEXT DEFAULT ''"
            )

    t = config.TABLE_NAME
    due = _payment_due_expr("NEW.")
    conn.executescript(
        f"""
        DROP TRIGGER IF EXISTS {t}_payment_due_ai;
        CREATE TRIGGER {t}_payment_due_ai
        AFTER INSERT ON {t}
        WHEN TRIM(COALESCE(NEW.payment_due, '')) = ''
         AND (TRIM(COALESCE(NEW.insurance_paid, '')) <> ''
              OR TRIM(COALESCE(NEW.payment_received, '')) <> '')
        BEGIN
            UPDATE {t} SET payment_due = {due} WHERE id = NEW.id;
        END;

        DROP TRIGGER IF EXISTS {t}_payment_due_au;
        CREATE TRIGGER {t}_payment_due_au
        AFTER UPDATE OF insurance_paid, payment_received ON {t}
        BEGIN
            UPDATE {t} SET payment_due = {due} WHERE id = NEW.id;
        END;
        """
    )

    # One-off: fill payment_due for rows already in the table that were
    # inserted before these triggers existed.
    conn.execute(
        f"""
        UPDATE {t} SET payment_due = {_payment_due_expr()}
        WHERE TRIM(COALESCE(payment_due, '')) = ''
          AND (TRIM(COALESCE(insurance_paid, '')) <> ''
               OR TRIM(COALESCE(payment_received, '')) <> '')
        """
    )
    conn.commit()


# ---------------------------------------------------------------------
# Date handling
# ---------------------------------------------------------------------

_DATE_PATTERNS = [
    "%m/%d/%Y %H:%M", "%m/%d/%Y %I:%M%p", "%m/%d/%Y %I:%M %p", "%m/%d/%Y",
    "%m/%d/%y %H:%M", "%m/%d/%y %I:%M%p", "%m/%d/%y %I:%M %p", "%m/%d/%y",
    "%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M", "%Y-%m-%d",
]


def extract_date_key(date_text):
    """Normalize a date string to YYYY-MM-DD for use in the de-dup key,
    so the same file always produces the same key. Falls back to the raw
    text if the format is unrecognized, so nothing is ever dropped."""
    raw = (date_text or "").strip()
    if not raw:
        return ""
    for pattern in _DATE_PATTERNS:
        try:
            return datetime.strptime(raw, pattern).strftime("%Y-%m-%d")
        except ValueError:
            continue
    match = re.match(r"(\d{1,4}[/-]\d{1,2}[/-]\d{1,4})", raw)
    if match:
        return match.group(1)
    return raw


def _clean_number(text):
    """'250.00' -> '250', '$1,892.20 ' -> '1892.2', '' -> ''. Leaves
    anything that isn't a number untouched (returns it stripped)."""
    stripped = (text or "").strip()
    try:
        value = float(stripped.replace(",", "").replace("$", "").strip())
    except ValueError:
        return stripped
    return str(int(value)) if value.is_integer() else str(value)


def _num(text):
    """Parse a money-ish string ('1,892.20', '$5', '') to a float;
    0.0 when it isn't a number."""
    cleaned = (text or "").replace(",", "").replace("$", "").strip()
    try:
        return float(cleaned or 0)
    except ValueError:
        return 0.0


_NULL_TOKENS = {"", "null", "none", "n/a", "na", "#n/a"}


def _cell(value):
    """Strip a CSV cell, treating literal 'NULL' / 'None' / 'N/A'
    placeholder text as an empty value."""
    stripped = (value or "").strip()
    return "" if stripped.lower() in _NULL_TOKENS else stripped


def _norm_header(text):
    """Like _normalize but keeps '$', so a 'Payment Received' header and a
    'Payment Received $' header map to different columns."""
    return re.sub(r"[^a-z0-9$]", "", str(text).lower())


# ---------------------------------------------------------------------
# Inserting rows (dedup-safe, manual-field-preserving)
# ---------------------------------------------------------------------

def insert_from_csv(conn, rows, source_file):
    """Insert parsed CSV rows. Only the CSV-sourced columns are written;
    manual fields keep their blank default on new rows and are never
    touched on existing ones. Rows whose (rx_number, filled_date) is
    already in the table are silently skipped via INSERT OR IGNORE."""
    csv_cols = [col for col, _ in config.CSV_FIELDS]
    placeholders = ", ".join("?" for _ in csv_cols)
    col_list = ", ".join(csv_cols)
    now = datetime.now().isoformat(timespec="seconds")

    new_count = 0
    for row in rows:
        values = [row.get(col, "") for col in csv_cols]
        cur = conn.execute(
            f"""
            INSERT OR IGNORE INTO {config.TABLE_NAME}
                ({col_list}, rx_number, filled_date, source_file, imported_at)
            VALUES ({placeholders}, ?, ?, ?, ?)
            """,
            values + [
                row.get("rx_number", ""),
                row.get("filled_date", ""),
                source_file,
                now,
            ],
        )
        if cur.rowcount:
            new_count += 1
    conn.commit()
    return new_count


def insert_backfill(conn, rows, source_file):
    """One-time history load from the old workbook (Daily Log + Billing).
    Writes every model column the backfill can supply. New rows are
    inserted; for a row that already exists (same rx_number +
    filled_date) only columns that are still blank get filled, so
    daily-import data and hand-typed edits are never overwritten.
    Returns (new_row_count, existing_rows_filled_count)."""
    fill_cols = [col for col, _ in config.ALL_FIELDS]
    insert_cols = fill_cols + ["rx_number", "filled_date", "source_file", "imported_at"]
    placeholders = ", ".join("?" for _ in insert_cols)
    update_clause = ", ".join(
        f"{c} = CASE WHEN TRIM(COALESCE({config.TABLE_NAME}.{c}, '')) = '' "
        f"THEN excluded.{c} ELSE {config.TABLE_NAME}.{c} END"
        for c in fill_cols
    )
    select_sql = (
        f"SELECT {', '.join(fill_cols)} FROM {config.TABLE_NAME} "
        f"WHERE rx_number = ? AND filled_date = ?"
    )
    now = datetime.now().isoformat(timespec="seconds")

    new_count = 0
    filled_count = 0
    for row in rows:
        key = (row.get("rx_number", ""), row.get("filled_date", ""))
        before = conn.execute(select_sql, key).fetchone()
        values = [row.get(c, "") for c in fill_cols] + [key[0], key[1], source_file, now]
        conn.execute(
            f"""
            INSERT INTO {config.TABLE_NAME} ({', '.join(insert_cols)})
            VALUES ({placeholders})
            ON CONFLICT(rx_number, filled_date) DO UPDATE SET
                {update_clause}
            """,
            values,
        )
        if before is None:
            new_count += 1
        elif tuple(before) != tuple(conn.execute(select_sql, key).fetchone()):
            filled_count += 1
    conn.commit()
    return new_count, filled_count


# ---------------------------------------------------------------------
# CSV parsing (NF Insurance report export)
# ---------------------------------------------------------------------

def read_nf_ins_csv(path):
    """Returns a list of dicts, one per non-formulary prescription.

    Each dict has the CSV-sourced database columns (name, drug, quantity,
    insurance_paid) plus rx_number and filled_date for the de-dup key.

    The export repeats the report letterhead on every line, then an
    'Ins.Code:' marker, then the prescription's data, then running
    totals. We locate the marker on each line and read the fixed
    CSV_FIELD_SEQUENCE that follows it (see config.py)."""
    marker_norm = _normalize(config.CSV_DATA_MARKER)

    with open(path, newline="", encoding="utf-8-sig") as f:
        raw_rows = list(csv.reader(f))

    raw_rows = [r for r in raw_rows if any(cell.strip() for cell in r)]

    rows = []
    for raw in raw_rows:
        marker_idx = None
        for idx, cell in enumerate(raw):
            if marker_norm and marker_norm in _normalize(cell):
                marker_idx = idx
                break
        if marker_idx is None:
            continue  # not a recognizable data line

        start = marker_idx + config.CSV_MARKER_TO_DATA_OFFSET
        fields = raw[start:start + len(config.CSV_FIELD_SEQUENCE)]
        if len(fields) < len(config.CSV_FIELD_SEQUENCE):
            continue  # truncated / malformed line

        raw_record = dict(zip(config.CSV_FIELD_SEQUENCE, (v.strip() for v in fields)))
        if not raw_record.get("rx_number"):
            continue  # totals row or stray text, not a prescription

        record = {k: v for k, v in raw_record.items() if not k.startswith("_")}
        record["filled_date"] = extract_date_key(record.get("filled_date", ""))
        rows.append(record)

    return rows


# ---------------------------------------------------------------------
# CSV parsing (old workbook "Daily Log" sheet export — one-time backfill)
# ---------------------------------------------------------------------

def _synthetic_rx(record):
    """A stable stand-in de-dup key for a backfill row that has no
    RX Number, derived from the row's own content. Two backfill rows
    identical across BACKFILL_HASH_FIELDS get the same key (so re-running
    the backfill merges rather than duplicates); anything that differs in
    drug / quantity / amount / etc. gets its own key and its own row.
    The "BF-" prefix can never collide with a real numeric RX Number."""
    basis = "|".join(
        (record.get(f, "") or "").strip().lower()
        for f in config.BACKFILL_HASH_FIELDS
    )
    return "BF-" + hashlib.sha1(basis.encode("utf-8")).hexdigest()[:12]


def read_backfill_csv(path):
    """Read the single backfill CSV (the old "Daily Log" sheet export,
    which now also carries the billing columns) as a flat table.

    Finds the header row via BACKFILL_COLUMN_MAP, then returns one dict
    per data row: the mapped model columns plus rx_number and filled_date
    for the hidden de-dup key. Literal 'NULL' / 'N/A' cells are treated as
    blank; numeric-ish columns are cleaned ('$3,779.40' -> '3779.4');
    filled_date is normalized to YYYY-MM-DD. `payment_due` is computed as
    insurance_paid - payment_received when it comes in blank. Rows with no
    RX Number get a content-hash key from _synthetic_rx(). Columns not in
    the map (e.g. "Claim Number", "Balance Due") are dropped."""
    number_cols = {"quantity", "insurance_paid", "payment_received", "payment_due"}

    with open(path, newline="", encoding="utf-8-sig") as f:
        raw_rows = [r for r in csv.reader(f) if any(c.strip() for c in r)]

    col_index = {}
    rows = []
    for raw in raw_rows:
        mapped = {
            i: config.BACKFILL_COLUMN_MAP[n]
            for i, n in ((idx, _norm_header(c)) for idx, c in enumerate(raw))
            if n in config.BACKFILL_COLUMN_MAP
        }

        if not col_index:
            # first row that looks like the header wins
            if "name" in mapped.values() and len(mapped) >= 4:
                col_index = mapped
            continue

        record = {
            db_col: _cell(raw[i] if i < len(raw) else "")
            for i, db_col in col_index.items()
        }
        if not any(record.get(c) for c in ("name", "rx_number", "drug")):
            continue  # blank / junk row

        record["filled_date"] = extract_date_key(record.get("filled_date", ""))
        for col in number_cols & record.keys():
            if record[col]:
                record[col] = _clean_number(record[col])

        if not (record.get("payment_due") or "").strip() and (
            (record.get("insurance_paid") or "").strip()
            or (record.get("payment_received") or "").strip()
        ):
            record["payment_due"] = "%.2f" % (
                _num(record.get("insurance_paid"))
                - _num(record.get("payment_received"))
            )

        record["_had_rx"] = bool(record.get("rx_number"))
        if not record["_had_rx"]:
            record["rx_number"] = _synthetic_rx(record)
        rows.append(record)

    return rows
