"""
pharmacy_common.py — shared engine used by the scripts.

Do NOT edit this file. All the settings you'd want to change live in
config.py instead.
"""

import csv
import re
import sqlite3
from datetime import datetime

import config

# ---------------------------------------------------------------------
# Text normalization
# ---------------------------------------------------------------------

def _normalize(text):
    """Lowercase and strip everything but letters/digits, so 'Ins.Code:',
    'ins code', and 'INSCODE' all compare equal."""
    return re.sub(r"[^a-z0-9]", "", str(text).lower())


# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------

def get_connection():
    config.BASE_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(config.DB_PATH))
    conn.row_factory = sqlite3.Row
    return conn


def ensure_schema(conn):
    """Creates the table from config.ALL_FIELDS if it doesn't exist yet.
    Columns are created in ALL_FIELDS order; manual fields get a blank
    default. rx_number + filled_date are hidden bookkeeping columns used
    only as the de-dup key."""
    col_defs = []
    for col, _ in config.ALL_FIELDS:
        default = " DEFAULT ''" if col in config.MANUAL_FIELD_NAMES else ""
        col_defs.append(f"{col} TEXT{default}")
    body = ",\n            ".join(col_defs)
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {config.TABLE_NAME} (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            {body},
            rx_number TEXT,
            filled_date TEXT,
            source_file TEXT,
            imported_at TEXT,
            UNIQUE(rx_number, filled_date)
        )
        """
    )
    conn.commit()


# ---------------------------------------------------------------------
# Date handling
# ---------------------------------------------------------------------

_DATE_PATTERNS = [
    "%m/%d/%Y %H:%M", "%m/%d/%Y %I:%M%p", "%m/%d/%Y %I:%M %p", "%m/%d/%Y",
    "%m/%d/%y %H:%M", "%m/%d/%y %I:%M%p", "%m/%d/%y %I:%M %p", "%m/%d/%y",
    "%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M", "%Y-%m-%d",
]


def extract_date_key(date_text):
    """Normalize a date string to YYYY-MM-DD for use in the de-dup key,
    so the same file always produces the same key. Falls back to the raw
    text if the format is unrecognized, so nothing is ever dropped."""
    raw = (date_text or "").strip()
    if not raw:
        return ""
    for pattern in _DATE_PATTERNS:
        try:
            return datetime.strptime(raw, pattern).strftime("%Y-%m-%d")
        except ValueError:
            continue
    match = re.match(r"(\d{1,4}[/-]\d{1,2}[/-]\d{1,4})", raw)
    if match:
        return match.group(1)
    return raw


# ---------------------------------------------------------------------
# Inserting rows (dedup-safe, manual-field-preserving)
# ---------------------------------------------------------------------

def insert_from_csv(conn, rows, source_file):
    """Insert parsed CSV rows. Only the CSV-sourced columns are written;
    manual fields keep their blank default on new rows and are never
    touched on existing ones. Rows whose (rx_number, filled_date) is
    already in the table are silently skipped via INSERT OR IGNORE."""
    csv_cols = [col for col, _ in config.CSV_FIELDS]
    placeholders = ", ".join("?" for _ in csv_cols)
    col_list = ", ".join(csv_cols)
    now = datetime.now().isoformat(timespec="seconds")

    new_count = 0
    for row in rows:
        values = [row.get(col, "") for col in csv_cols]
        cur = conn.execute(
            f"""
            INSERT OR IGNORE INTO {config.TABLE_NAME}
                ({col_list}, rx_number, filled_date, source_file, imported_at)
            VALUES ({placeholders}, ?, ?, ?, ?)
            """,
            values + [
                row.get("rx_number", ""),
                row.get("filled_date", ""),
                source_file,
                now,
            ],
        )
        if cur.rowcount:
            new_count += 1
    conn.commit()
    return new_count


# ---------------------------------------------------------------------
# CSV parsing (NF Insurance report export)
# ---------------------------------------------------------------------

def read_nf_ins_csv(path):
    """Returns a list of dicts, one per non-formulary prescription.

    Each dict has the CSV-sourced database columns (name, drug, quantity,
    insurance_paid) plus rx_number and filled_date for the de-dup key.

    The export repeats the report letterhead on every line, then an
    'Ins.Code:' marker, then the prescription's data, then running
    totals. We locate the marker on each line and read the fixed
    CSV_FIELD_SEQUENCE that follows it (see config.py)."""
    marker_norm = _normalize(config.CSV_DATA_MARKER)

    with open(path, newline="", encoding="utf-8-sig") as f:
        raw_rows = list(csv.reader(f))

    raw_rows = [r for r in raw_rows if any(cell.strip() for cell in r)]

    rows = []
    for raw in raw_rows:
        marker_idx = None
        for idx, cell in enumerate(raw):
            if marker_norm and marker_norm in _normalize(cell):
                marker_idx = idx
                break
        if marker_idx is None:
            continue  # not a recognizable data line

        start = marker_idx + config.CSV_MARKER_TO_DATA_OFFSET
        fields = raw[start:start + len(config.CSV_FIELD_SEQUENCE)]
        if len(fields) < len(config.CSV_FIELD_SEQUENCE):
            continue  # truncated / malformed line

        raw_record = dict(zip(config.CSV_FIELD_SEQUENCE, (v.strip() for v in fields)))
        if not raw_record.get("rx_number"):
            continue  # totals row or stray text, not a prescription

        record = {k: v for k, v in raw_record.items() if not k.startswith("_")}
        record["filled_date"] = extract_date_key(record.get("filled_date", ""))
        record["insurance_paid"] = config.INSURANCE_PAID_VALUE
        rows.append(record)

    return rows
