"""
pharmacy_common.py — shared engine used by all three scripts.

Do NOT edit this file. All the settings you'd want to change live in
config.py instead.
"""

import csv
import re
import sqlite3
from datetime import datetime

import config

# ---------------------------------------------------------------------
# Text / header normalization helpers
# ---------------------------------------------------------------------

def _normalize(text):
    """Lowercase and strip everything but letters/digits, so 'Rx #',
    'rx#', and 'RX_Number' all compare equal."""
    return re.sub(r"[^a-z0-9]", "", str(text).lower())


def build_alias_lookup(fields):
    """fields: list of (db_column, label). Returns a dict mapping
    normalized label text -> db_column."""
    return {_normalize(label): db_col for db_col, label in fields}


# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------

def get_connection():
    config.BASE_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(config.DB_PATH))
    conn.row_factory = sqlite3.Row
    return conn


def ensure_schema(conn):
    auto_cols = ", ".join(f"{col} TEXT" for col, _ in config.AUTO_FIELDS)
    manual_cols = ", ".join(f"{col} TEXT DEFAULT ''" for col, _ in config.MANUAL_FIELDS)
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS daily_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            {auto_cols},
            date_filled TEXT,
            {manual_cols},
            source_file TEXT,
            imported_at TEXT,
            UNIQUE(rx_number, date_filled)
        )
        """
    )
    conn.commit()


# ---------------------------------------------------------------------
# Date handling
# ---------------------------------------------------------------------

_DATE_PATTERNS = [
    "%m/%d/%Y %H:%M", "%m/%d/%Y %I:%M%p", "%m/%d/%Y %I:%M %p", "%m/%d/%Y",
    "%m/%d/%y %H:%M", "%m/%d/%y %I:%M%p", "%m/%d/%y %I:%M %p", "%m/%d/%y",
    "%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M", "%Y-%m-%d",
]


def extract_date_key(date_text):
    """Pull a normalized YYYY-MM-DD date out of a date or date/time
    string, so 'Rx # + Date Filled' can be used as the dedup key even
    though PrimeRx's export includes a time. Falls back to the raw text
    if it doesn't match a known format, so nothing is ever silently
    dropped."""
    raw = (date_text or "").strip()
    if not raw:
        return ""
    for pattern in _DATE_PATTERNS:
        try:
            return datetime.strptime(raw, pattern).strftime("%Y-%m-%d")
        except ValueError:
            continue
    match = re.match(r"(\d{1,4}[/-]\d{1,2}[/-]\d{1,4})", raw)
    if match:
        return match.group(1)
    return raw


def format_cell(value):
    """Turn an Excel cell value into clean text: dates as MM/DD/YYYY,
    whole-number floats without a trailing '.0' (openpyxl returns Rx #
    and Qty as floats), everything else stripped."""
    if value is None:
        return ""
    if isinstance(value, datetime):
        return value.strftime("%m/%d/%Y")
    if isinstance(value, float):
        return str(int(value)) if value.is_integer() else str(value)
    return str(value).strip()


# ---------------------------------------------------------------------
# Inserting rows (dedup-safe, manual-field-preserving)
# ---------------------------------------------------------------------

def insert_auto_only(conn, rows, source_file):
    """Used by the daily CSV import. Manual fields are never included,
    so an existing row's manual fields (typed in by hand) are never
    touched. Rows that already exist (same Rx # + Date Filled) are
    silently skipped via INSERT OR IGNORE."""
    auto_cols = [col for col, _ in config.AUTO_FIELDS]
    placeholders = ", ".join("?" for _ in auto_cols)
    col_list = ", ".join(auto_cols)
    now = datetime.now().isoformat(timespec="seconds")

    new_count = 0
    for row in rows:
        date_key = extract_date_key(row.get("date_time_filled", ""))
        values = [row.get(col, "") for col in auto_cols]
        cur = conn.execute(
            f"""
            INSERT OR IGNORE INTO daily_log
                ({col_list}, date_filled, source_file, imported_at)
            VALUES ({placeholders}, ?, ?, ?)
            """,
            values + [date_key, source_file, now],
        )
        if cur.rowcount:
            new_count += 1
    conn.commit()
    return new_count


def upsert_with_manual_fields(conn, rows, source_file):
    """Used by the one-time Excel backfill. Inserts new rows with both
    auto AND manual fields. If a row already exists (e.g. a daily
    import already created it), any of ITS manual fields that are still
    blank get filled in from the backfill data — but manual fields that
    already have a value are left alone, so nobody's typed-in notes get
    clobbered no matter which script ran first."""
    auto_cols = [col for col, _ in config.AUTO_FIELDS]
    manual_cols = [col for col, _ in config.MANUAL_FIELDS]
    all_cols = auto_cols + manual_cols
    placeholders = ", ".join("?" for _ in all_cols)
    col_list = ", ".join(all_cols)
    update_clause = ", ".join(
        f"{col} = CASE WHEN TRIM(COALESCE(daily_log.{col}, '')) = '' "
        f"THEN excluded.{col} ELSE daily_log.{col} END"
        for col in manual_cols
    )
    now = datetime.now().isoformat(timespec="seconds")

    new_count = 0
    filled_count = 0
    for row in rows:
        date_key = row.get("date_filled", "")
        values = [row.get(col, "") for col in all_cols]
        before = conn.execute(
            "SELECT " + ", ".join(manual_cols) +
            " FROM daily_log WHERE rx_number = ? AND date_filled = ?",
            (row.get("rx_number", ""), date_key),
        ).fetchone()

        conn.execute(
            f"""
            INSERT INTO daily_log ({col_list}, date_filled, source_file, imported_at)
            VALUES ({placeholders}, ?, ?, ?)
            ON CONFLICT(rx_number, date_filled) DO UPDATE SET
                {update_clause}
            """,
            values + [date_key, source_file, now],
        )
        if before is None:
            new_count += 1
        else:
            after = conn.execute(
                "SELECT " + ", ".join(manual_cols) +
                " FROM daily_log WHERE rx_number = ? AND date_filled = ?",
                (row.get("rx_number", ""), date_key),
            ).fetchone()
            if tuple(before) != tuple(after):
                filled_count += 1
    conn.commit()
    return new_count, filled_count


# ---------------------------------------------------------------------
# CSV parsing (PrimeRx Daily Log Report export)
# ---------------------------------------------------------------------

def read_primerx_csv(path):
    """Returns a list of dicts keyed by AUTO_FIELDS db_column names.

    The real export repeats the pharmacy's letterhead and the report's
    column titles on EVERY line, followed by that line's actual
    prescription data. We find each line's data by locating the
    '*** Daily Log For : ... ***' marker field and reading the fixed
    sequence of fields that immediately follows it (see
    CSV_DATA_MARKER / CSV_FIELD_SEQUENCE in config.py)."""
    marker_norm = config.CSV_DATA_MARKER.replace(" ", "")

    with open(path, newline="", encoding="utf-8-sig") as f:
        raw_rows = list(csv.reader(f))

    raw_rows = [r for r in raw_rows if any(cell.strip() for cell in r)]

    rows = []
    for raw in raw_rows:
        marker_idx = None
        for idx, cell in enumerate(raw):
            if marker_norm in _normalize(cell):
                marker_idx = idx
                break
        if marker_idx is None:
            continue  # not a recognizable PrimeRx data line

        start = marker_idx + config.CSV_MARKER_TO_DATA_OFFSET
        fields = raw[start:start + len(config.CSV_FIELD_SEQUENCE)]
        if len(fields) < len(config.CSV_FIELD_SEQUENCE):
            continue  # truncated/malformed line

        raw_record = dict(zip(config.CSV_FIELD_SEQUENCE, (v.strip() for v in fields)))
        if not raw_record.get("rx_number"):
            continue

        record = {k: v for k, v in raw_record.items() if not k.startswith("_")}
        date_raw = raw_record.get("_date_raw", "").strip()
        time_raw = raw_record.get("_time_raw", "").strip()
        record["date_time_filled"] = f"{date_raw} {time_raw}".strip()
        rows.append(record)

    return rows


# ---------------------------------------------------------------------
# Excel Daily Log tab parsing (backfill)
# ---------------------------------------------------------------------

def get_table_column_map(sheet, table_name, alias_map):
    """Returns (col_index_map, header_row, first_data_row, last_row)
    using the sheet's actual Excel Table definition, so we read the
    real column order instead of guessing at header text. Returns None
    if the named table isn't found on this sheet."""
    from openpyxl.utils.cell import range_boundaries

    table = sheet.tables.get(table_name) if hasattr(sheet.tables, "get") else None
    if table is None:
        return None

    min_col, min_row, max_col, max_row = range_boundaries(table.ref)
    header_row = min_row
    col_map = {}
    for i, table_col in enumerate(table.tableColumns):
        db_col = alias_map.get(_normalize(table_col.name))
        if db_col:
            col_map[min_col + i] = db_col
    return col_map, header_row, header_row + 1, max_row


def read_daily_log_sheet(sheet):
    """Returns a list of dicts (auto + manual fields, plus date_filled)
    from the '📋 Daily Log' Excel Table. Handles the 'Log Date:M/D/YY'
    separator rows your old Office Script inserts by carrying that date
    forward onto the data rows beneath it, until the next separator."""
    alias_map = dict(config.EXCEL_COLUMN_ALIASES)

    table_info = get_table_column_map(sheet, config.EXCEL_TABLE_NAME, alias_map)
    used_fallback = False
    if table_info is None:
        used_fallback = True
        col_map, header_row, first_data_row, last_row = _find_header_row_fallback(
            sheet, alias_map
        )
        if col_map is None:
            return None, used_fallback
    else:
        col_map, header_row, first_data_row, last_row = table_info

    patient_col = next((c for c, f in col_map.items() if f == "patient"), None)
    rx_col = next((c for c, f in col_map.items() if f == "rx_number"), None)

    rows = []
    current_log_date = ""
    unknown_counter = 0
    skipped_separator = 0

    for row_idx in range(first_data_row, last_row + 1):
        record = {}
        any_value = False
        for col, db_col in col_map.items():
            val = format_cell(sheet.cell(row=row_idx, column=col).value)
            if val:
                any_value = True
            record[db_col] = val

        if not any_value:
            continue  # fully blank row

        patient_val = record.get("patient", "") if patient_col else ""
        norm_patient = _normalize(patient_val)
        if norm_patient.startswith(_normalize(config.EXCEL_LOG_DATE_PREFIX)):
            # "Log Date:6/17/26" separator row — remember the date for
            # the rows that follow, don't treat it as data.
            date_part = re.split(r":", patient_val, maxsplit=1)
            if len(date_part) == 2:
                current_log_date = extract_date_key(date_part[1].strip())
            skipped_separator += 1
            continue

        rx_val = record.get("rx_number", "") if rx_col else ""
        if not rx_val:
            continue  # not a real data row (banner/blank/other stray text)

        for col_name, _ in config.ALL_FIELDS:
            record.setdefault(col_name, "")

        if current_log_date:
            record["date_filled"] = current_log_date
        else:
            unknown_counter += 1
            record["date_filled"] = f"UNKNOWN-ROW-{row_idx}"

        rows.append(record)

    meta = {
        "used_fallback": used_fallback,
        "skipped_separator": skipped_separator,
        "unknown_date_count": unknown_counter,
    }
    return rows, meta


def _find_header_row_fallback(sheet, alias_map, search_rows=15):
    """Used only if EXCEL_TABLE_NAME isn't found on the sheet (e.g. the
    real workbook doesn't use a formal Excel Table). Scans the first
    few rows for one that looks like a header, matching config's
    EXCEL_COLUMN_ALIASES."""
    best_row_idx = None
    best_score = 0
    for row_idx in range(1, min(search_rows, sheet.max_row) + 1):
        row_cells = [sheet.cell(row=row_idx, column=c).value for c in range(1, sheet.max_column + 1)]
        score = sum(1 for cell in row_cells if cell and _normalize(cell) in alias_map)
        if score > best_score:
            best_score = score
            best_row_idx = row_idx
    if best_score < 3:
        return None, None, None, None

    col_map = {}
    for c in range(1, sheet.max_column + 1):
        header_val = sheet.cell(row=best_row_idx, column=c).value
        if header_val is None:
            continue
        db_col = alias_map.get(_normalize(header_val))
        if db_col:
            col_map[c] = db_col
    return col_map, best_row_idx, best_row_idx + 1, sheet.max_row
